// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/dmarins/stress-test-challenge-go/internal/infrastructure/http"
	"github.com/dmarins/stress-test-challenge-go/internal/usecase"
)

// Injectors from wire.go:

// InitializeStressTest sets up the dependencies for StressTest using Google Wire.
func InitializeStressTest() *usecase.StressTest {
	httpClientInterface := http.NewHttpClient()
	stressTest := usecase.NewStressTest(httpClientInterface)
	return stressTest
}
